### PR TITLE
Cocoapods spec

### PR DESCRIPTION
**Pull request by loicgriffie**
If you are ok with the cocoapods file you can just pusblish on cocoapods spec repos but before you do so, create a tag 1.0 of the repo

`pod trunk push NAME.podspec`

### CODE REVIEW

**Comment by chriswill0w** [comment]
@Appsido I think you have to make the convenience init of the UIAlertController public. Otherwise it will not compile.

**Comment by loicgriffie** [comment]
@ltblueberry0 You may be right. I'll check that and more probably declare as open may be better than public

**Comment by chriswill0w** [comment]
@Appsido the method "addAction" and maybe some others need public/open, too.

**Comment by loicgriffie** [comment]
@ltblueberry0 A lot of code change to make class + func public.

@dillidon Do you eventually plan to merge the request once work done ?

**Comment by afshin-hoseini** [comment]
@dillidon When do you plan to pull this?

**Comment by dillidon** [comment]
@afshin-hoseini sure, I've just pull some updates and going to do this task...

**Comment by loicgriffie** [comment]
@dillidon seems you are not willing to merge my pull request. May I have your feedback why ?

**Pull request closed without merging**
